### ISSUE TITLE
removeVirtualAreas does not correct district balances

### ISSUE THREAD

**Issue by janusdebondt** [rte-antares-rpackage/antaresRead#119]
The removeVirtualAreas function correctly corrects the balances of areas, but it seems that it does not correct the balances of districts. The behavior was observed when removing a virtual production area, but it seems that it will also be a problem for removing storageFlexibility areas.

**Comment by janusdebondt** [comment]
After further review, the problem seems not to be limited to the correction of the balance. It seems like the function removeVirtualAreas is not functioning at all correctly on the districts.

**Comment by jalazawa** [comment]
Thanks for you message, removeVirtualAreas is a complicated function.... 

Currently, `removeVirtualAreas` corrects only the data for areas, it's explained in the help 

````
removeVirtualAreas performs different corrections:

Correct the balance of the real areas by removing the flows to or from virtual areas.

...... 
````

More information [here](https://cran.r-project.org/web/packages/antaresRead/antaresRead.pdf)

If you want, you can see all tests for removeVirtualAreas [here](https://github.com/rte-antares-rpackage/antaresRead/blob/master/tests/testthat/test-removeVirtualAreas.R). 

In the beginning, we have excluded districts because it's more complicated like in this example 

![district](https://user-images.githubusercontent.com/22026724/45166170-b154dc80-b1f6-11e8-9393-857372c5acad.png)

C - A is a district. 
B - A is also a district. 

If we remove a virtual area D (not shown here), it will be a little more complicated to process the data. 

Another example if area D is connected to several areas in the same district (C and A), it will be complicated to calculate the BALANCE. 

If we remove A because it's a virtual area, it will be also complicated to correct the two districts (there are more areas than two areas in one district...). 

To be able to process this, I think, we must also import all the areas included in the district (more data in the RAM). We must check the presence of this data. 

But maybe the solution is simple, we can maybe sum the areas variables in the end of this process... BALANCE, COST. 

If you want, you can propose an idea :-)

**Comment by jalazawa** [comment]
I am writing the correction today. 

What I will correct?

Example 

![shema](https://user-images.githubusercontent.com/22026724/45668818-66a06200-bb1e-11e8-8b97-e714b87e4a53.png)

If we have these virtual areas  "psp in", "psp in-2", "psp out", "psp out-2", "hub"  and "a_offshore" then the BALANCE of the district (a and b) after removeVirtualAreas will be the sum of the BALANCE of "a" and "b". 
The district BALANCE (a - b) will also be equal to the flow between b and c. 

@janusdebondt are you agree? 

I will also correct the process of cost reassignment to correct district costs. 

actually we have : 

` If parameter reassignCosts is TRUE, then the costs of the virtual areas are reassigned to the real areas they are connected to. The affected columns are OV. COST, OP. COST, CO2 EMIS. and NP COST. `

**Comment by jalazawa** [comment]
Maybe we can also include this correction to removeVirtualAreas 

https://github.com/rte-antares-rpackage/antaresProcessing/issues/33

**Comment by janusdebondt** [comment]
@jalazawa I agree with the rationale of your proposed correction, however I also noticed that virtual production might also not be correctly assigned to the districts. I was thinking whether the groupByDistrict function could be used here?

**Comment by jalazawa** [comment]
I will check if we can use .groupByDistrict. Aggregate ANTARES data is sometime dangerous, because ANTARES write only integers but does the calculation with double. We may lose some precision if we use groupByDistrict for all variables. 

.groupByDistrict error : 

Error max by timeID : 1 
number time ID : 8760 
areas number : N 

Max error for the year for one variable : N*8760*1 MWh = N*8,760 TWh 

Example 
Wind(1, "a) = 1.2 ANTARES will write 1 in the file for area a 
Wind(1, "b) = 1.4 ANTARES will write 1 in the file for area b 

Wind(1, "district a and b") = 2.6 ANTARES will write 3 in the file for district a and b !

**Comment by jalazawa** [comment]
DONE, antaresRead 2.2.0 is on CRAN
