### ISSUE TITLE
Compatibilité entre la V7 d'Antares et readAntares(LinkCapacity = True)

### ISSUE THREAD

**Issue by MathildeFranconRTE** [rte-antares-rpackage/antaresRead#129]
Dans la V7, il y a 8 colonnes dans les fichiers .txt  pour décrire les liens contre 5 colonnes dans la V6). Probablement à cause de ça, la fonction readAntares ne permet plus d'importer les capacités des liens avec le paramètre LinkCapacity = TRUE.

Error in setnames(inputTS, names(inputTS), c("area", "timeId", colnames)) : 
  'old' is length 10 but 'new' is length 7
In addition: Warning message:
In readAntares(areas = Zones, links = getLinks(areas = getAreas(exclude = "td"),  :
  When misc, hydroStorageMaxPower, reserve or linkCapacity is not null, 'readAntares' reads input time series. Result may be wrong if these time series have changed since the simulation has been run. "

**Comment by pvictor** [comment]
Bonjour,
Quelle version d'Antares utilisez-vous ? Et quelle version du package `antaresRead` ?
Pouvez-vous essayer après avoir installé la version de développement du package ? Vous pouvez l'installer avec : 

```
remotes::install_github("rte-antares-rpackage/antaresRead")
``` 

Victor

**Comment by MathildeFranconRTE** [comment]
En effet, ça fonctionne avec cette version du package ! Merci

**Comment by pvictor** [comment]
Parfait! Nous tenterons une release sur le CRAN la semaine prochaine.

**Comment by Jean-YvesBourmaudRTE** [comment]
Bonjour,
J'ai l'impression que je tombe sur le même problème, mais la solution proposée ne l'a pas réglé.

Je suis sous Antarès V7.0.0
Je tente l'opération suivante :
essai=readAntares(areas = getAreas(), links = getLinks(areas = getAreas()), linkCapacity=TRUE)
Et j'obtiens la sortie suivante, terminant par un message d'erreur :
Importing areas
  |===============================================================================| 100%
Importing links
  |===============================================================================| 100%
Importing linkCapacity
  |                                                                               |   0%Error in setnames(inputTS, names(inputTS), c("area", "timeId", colnames)) : 
  'old' is length 10 but 'new' is length 7
In addition: Warning message:
In readAntares(areas = getAreas(), links = getLinks(areas = getAreas()),  :
  When misc, hydroStorageMaxPower, reserve or linkCapacity is not null, 'readAntares' reads input time series. Result may be wrong if these time series have changed since the simulation has been run.

Alors que si je ne mentionne pas le paramètres linkCapacity, ça passe.
essai=readAntares(areas = getAreas(), links = getLinks(areas = getAreas()))
Importing areas
  |===============================================================================| 100%
Importing links
  |===============================================================================| 100%

Merci.
Cordialement.
JY Bourmaud
